In [6]:
import pandas as pd
cust = pd.read_csv("C:\\Users\\lakshraj computer\\Downloads\\QuickCart_Assessment_Keval_Chauhan\\quickcart_data\\customers.csv")
cust.head()

,customer_id,signup_date,city,age,gender,plan_type,acquisition_channel,account_status
0,C00001,2025-07-27,Bengaluru,23.0,F,free,organic,active
1,C00002,2026-02-18,Pune,35.0,M,plus,organic,active
2,C00003,2026-01-13,Jaipur,26.0,F,free,referral,active
3,C00004,2025-11-09,Bengaluru,18.0,M,premium,google_ads,active
4,C00005,2025-11-07,Ahmedabad,29.0,M,free,referral,active

In [7]:
ord = pd.read_csv("C:\\Users\\lakshraj computer\\Downloads\\QuickCart_Assessment_Keval_Chauhan\\quickcart_data\\orders.csv")
ord.head()

,order_id,customer_id,order_ts,basket_value,items_count,discount_amt,distance_km,store_open_orders,is_raining,delivery_minutes,payment_method,status
0,O0065098,C02442,2025-07-02 04:25:57.424918,518.71,13,0.00,1.63,4,0,20.5,COD,delivered
1,O0040713,C01550,2025-07-03 03:51:16.974293,429.40,10,21.47,1.77,15,0,26.6,card,delivered
2,O0085074,C03191,2025-07-03 04:56:28.375695,298.22,7,14.91,1.83,4,1,26.5,card,delivered
3,O0022172,C00845,2025-07-03 14:19:33.378437,296.85,3,0.00,1.96,5,0,14.5,UPI,refunded
4,O0086160,C03234,2025-07-03 14:41:18.888420,697.31,13,139.46,2.36,26,1,34.3,UPI,delivered

In [8]:
cust.info()

<class 'pandas.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customer_id          4000 non-null   str
 1   signup_date          4000 non-null   str
 2   city                 4000 non-null   str
 3   age                  3940 non-null   float64
 4   gender               4000 non-null   str
 5   plan_type            4000 non-null   str
 6   acquisition_channel  4000 non-null   str
 7   account_status       4000 non-null   str
dtypes: float64(1), str(7)
memory usage: 418.0 KB

In [9]:
ord.info()

<class 'pandas.DataFrame'>
RangeIndex: 106592 entries, 0 to 106591
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   order_id           106592 non-null  str
 1   customer_id        106592 non-null  str
 2   order_ts           106592 non-null  str
 3   basket_value       106592 non-null  float64
 4   items_count        106592 non-null  int64
 5   discount_amt       106592 non-null  float64
 6   distance_km        106592 non-null  float64
 7   store_open_orders  106592 non-null  int64
 8   is_raining         106592 non-null  int64
 9   delivery_minutes   101352 non-null  float64
 10  payment_method     106592 non-null  str
 11  status             106592 non-null  str
dtypes: float64(4), int64(3), str(5)
memory usage: 15.1 MB

In [10]:
cust.isna().sum()

customer_id             0
signup_date             0
city                    0
age                    60
gender                  0
plan_type               0
acquisition_channel     0
account_status          0
dtype: int64

In [11]:
ord.isna().sum()

order_id                0
customer_id             0
order_ts                0
basket_value            0
items_count             0
discount_amt            0
distance_km             0
store_open_orders       0
is_raining              0
delivery_minutes     5240
payment_method          0
status                  0
dtype: int64